### ISSUE TITLE
REQUEST: New membership

### ISSUE THREAD

**Issue by Arhell** [devstream-io/devstream#1207]
### GitHub Username

@Arhell

### List of contributions to the devstream project

https://github.com/devstream-io/website/issues/91
https://github.com/devstream-io/website/commits?author=Arhell

I want to support the project and help fix bugs and other problems that I find.

https://github.com/devstream-io/website
https://github.com/devstream-io/blog
https://github.com/devstream-io/devstream/tree/main/docs

Thank you for your attention

**Comment by IronCore864** [comment]
Hi @Arhell, thanks for your previous contribution. Since you are already contributing, by definition, you are already a contributor. Kudos on that!

Read [here](https://docs.devstream.io/en/release-0.9/contributing_guide/) for how to contribute more :)

If you would like to participate more and get promoted to the next level (member, reviewer, etc.), please read the [contributor growth ladder](https://docs.devstream.io/en/release-0.9/contributor_ladder/#reviewer).
