### ISSUE TITLE
This is amazing, i want to integrate our service as one of your DevOps Tools

### ISSUE THREAD

**Issue by cosmic-flood** [devstream-io/devstream#273]
## Question

How can i join your project?

I am a Chinese feature flags provider (feature-flags.co). I found that this is a very cool project. Imagine that someone would create a very common infrastructure + cooperation + devops system, and then i can just copy the .yaml file then i get the same great system like what "someone (maybe big company)" have.

This is just a "breathtaking" project!!

**Comment by IronCore864** [comment]
Hi @cosmic-flood. Thanks a lot for your interest! This is a huge inspiration for us!

I suggest a quick demo with your team so that we know how it works, how it's installed, and how it can integrate and interact with other tools. After that, we may also do a quick demo session on developing a new plugin.

Thanks again for your interest and potential contributions :)
