### ISSUE TITLE
🍀 `Proposal`: Support to download the plugin files from a proxy server

### ISSUE THREAD

**Issue by LinuxSuRen** [devstream-io/devstream#379]
## Description

When I try to use `dtm` to do something. I got the connection timeout errors. It might be pretty common for the Chinese users, the connection to GitHub release URL is not stable in China.

## Describe the Proposal

So, I am thinking if it's possible to let `dtm` downloads those files from a proxy server. Of course, it would be better to let users choose this behavior. For example, we can provide a flag to choose whether to use a proxy server. This flag would be a global flag:

`dtm --gh-proxy xxx init xxx`

I have already done that in this project [http-downloader](https://github.com/LinuxSuRen/http-downloader/). Please feel free to write your comments below. I'd be happy to improve this if you believe this is ok.

> By the way, in case of anyone wants to try download `dtm` using the tool which I mentioned. You can try this command: `hd install stream`

## Has the Feature been Requested Before?

Nope.

## Describe the Alternatives You Have Considered

Nope.

## Additional Context

Nope.

**Comment by daniel-hutao** [comment]
You are right, using `dtm` in China will indeed face network problems, and we have also thought about whether to store all the `plugins` in a domestic cloud storage.

If we are using a proxy, there may be two ways.
- One is to add a flag to specify the proxy as you said,
- And the other is to directly `export http_proxy ...` to implement the proxy mode without intrusion.

For users who do not have proxy software in hand, they may need the cloud storage I mentioned earlier to solve the download problem.
For the other users, maybe the `export ...` method simpler?

**Comment by daniel-hutao** [comment]
As for the download of `dtm`(DevStream cli) itself, maybe `hd` is a good way, I don't know what other people think. @devstream-io/pmc

**Comment by LinuxSuRen** [comment]
There are a few free proxy servers that we can use. See also [here](https://github.com/LinuxSuRen/http-downloader/blob/d72756da9d7e131f8515fba0807ca1654cc5f887/cmd/get.go#L62).

**Comment by daniel-hutao** [comment]
> There are a few free proxy servers that we can use. See also [here](https://github.com/LinuxSuRen/http-downloader/blob/d72756da9d7e131f8515fba0807ca1654cc5f887/cmd/get.go#L62).

It seems cool!

**Comment by daniel-hutao** [comment]
I think it's ok to add a `--gh-proxy` or `--proxy` flag to let `dtm` downloads plugins from a proxy server. We could set a default free proxy server and reserve the right to choose which proxy to use with this flag.

**Comment by IronCore864** [comment]
This is actually a great idea.

I think we should use `--proxy` instead of `--gh-proxy` because in the near future we might need to publish the artifacts to AWS S3 or equivalent instead of GitHub. So the `--proxy` fits future plans better. 

@daniel-hutao please create a simple and small design for this feature, and thanks a lot for @LinuxSuRen this great contribution!

**Comment by daniel-hutao** [comment]
Hi Rick @LinuxSuRen , Thank you for the great proposal!

I wrote some considerations here, maybe not being completely accurate. But I hope these suggestions will help you.

- Flag name: proxy(--proxy), maybe `-p` is not needed, because `-p` is easy to confuse with `port`
- This flag should be global, not used by `init` alone, because other commands may also need to download some "dependencies". (`rootCMD.PersistentFlags()`)
- The default value with this flag should be a `free proxy` address mentioned in your comment above.

---

- `hd install dtm` is indeed a good solution to resolve the network problem of `dtm` itself, what is your opinion? If you agree with this approach, perhaps we can document this approach in the "installation step" at README.md in a separate pr. 
- If we decide to do it, of course the most suitable performer for this task is @LinuxSuRen . But `hd` itself needs to be downloaded from github, so, you know what I mean.

**Comment by LinuxSuRen** [comment]
hi @daniel-hutao , thanks for your details. That's great.

Consider the use case of downloading a file from the GitHub release is pretty common. I'm thinking about if it's possible to reuse [http-downloader](https://github.com/LinuxSuRen/http-downloader/) project. That means if it's possible to do the most work in the project `hd`, than reuse it in the `devstream` project.

**Comment by daniel-hutao** [comment]
Wait a minute, just hang up first, maybe my previous answer was not rigorous enough, let's discuss internally more for the `best practices`, and I'll update the "final" suggestion here later.

**Comment by IronCore864** [comment]
After second thought, I don't think depending on a few fixed third-party proxies like "gh.api.99988866.xyz", "ghproxy.com", "mirror.ghproxy.com", etc., is the best we can do because they might be subject to change.

I think a more generic solution would be to publish *.so files in an object store inside the GFW. What do you guys think?

**Comment by LinuxSuRen** [comment]
It's ok to publish those plugin files to any place. But for a contributor, it is best to let all people can see the files easily. This can allow more people to be able to improve it. And I don't recommend having multiple places for different people who are in different countries. The potential users and contributors might come from any place. To make it be short, I think the GitHub release is good enough.

Of course, this is just my personal perspective.

**Comment by IronCore864** [comment]
@LinuxSuRen after a discussion with Daniel, we decided to wait a little bit before implementing this feature, mainly because of another high-priority task. Please keep this thread open, and let's revisit it again soon (hopefully in 2 weeks).

**Comment by daniel-hutao** [comment]
See also #23

**Comment by LinuxSuRen** [comment]
> See also #23

So, I guess we can track this issue in #23 . And I can close this issue now. Right?
