### ISSUE TITLE
Proposal: View all supported plugins with the list command

### ISSUE THREAD

**Issue by summingyu** [devstream-io/devstream#384]
## Description

View all supported plugins by list command, and support group display

**Comment by daniel-hutao** [comment]
Great idea! @summingyu 

It's a good idea to get the names of all dtm supported plugins directly from the command line. Because it is really cumbersome to query which plugins are available through the documentation.

Since there are not many plugins at present, I recommend outputting all the plugins' names directly without grouping. 

When there are more plugins are supported in the future, we could implement group output at that time, even output all plugins' names of a group by specifying the group name like `--group=ci` or `--kind=ci`.

Go back to the implementation, I briefly thought about it, maybe we can design the command like:
- `dtm list-plugins`

Maybe we can use the `dtm list-plugins --kind=ci` at future to support `group output`.

Of course there are many other options, I also list them for consideration
- `dtm list plugins`
- `dtm plugins list`

/cc @devstream-io/pmc

**Comment by IronCore864** [comment]
Great idea @summingyu

`list-plugins`, `list-plugins --kind=ci` look quite natural to my eyes.

Let's go!
