### ISSUE TITLE
Proposal: Update the welcome message of dtm cli-tool

### ISSUE THREAD

**Issue by hxcGit** [devstream-io/devstream#440]
## Description
`Devstream` is a very interesting program, I just followed it and learned about it through quick start. Could we set the welcome message "DEVSTREAM" to the same height?
## Describe the Proposal
I guess the goal of the original design was to highlight the letters `D` and `S`. But in this case, all the letters are capitalized, could we adjust all the letters to the same height.

I have conducted relevant experiments and the comparative results are as follows.
- Before
<img width="920" alt="image" src="https://user-images.githubusercontent.com/60642406/166428582-59922914-3345-4efc-bfba-11952a0155d1.png">

- Update
<img width="920" alt="image" src="https://user-images.githubusercontent.com/60642406/166428676-c2c6c1e1-5da5-4af7-bc09-333a1e69116d.png">

Looking forward to your consideration

**Comment by daniel-hutao** [comment]
@IronCore864 Please take a look at this proposal.

**Comment by IronCore864** [comment]
@hxcGit we tried to avoid using all caps because it would feel like yelling.

We also considered using "DevStream" (a mix of upper and lower case) but smaller characters don't look so nice as ASCII art.

That's why we used the current form: it doesn't look as "yelling" as all caps, and the smaller characters look nicer than what lower case characters would look like.

As long as we don't use ALL CAPS, we are open to a change. Please make some proposals.

Thanks again! @hxcGit

@daniel-hutao please also have a look; see if it's reasonable.

**Comment by hxcGit** [comment]
> @hxcGit we tried to avoid using all caps because it would feel like yelling.
> 
> We also considered using "DevStream" (a mix of upper and lower case) but smaller characters don't look so nice as ASCII art.
> 
> That's why we used the current form: it doesn't look as "yelling" as all caps, and the smaller characters look nicer than what lower case characters would look like.
> 
> As long as we don't use ALL CAPS, we are open to a change. Please make some proposals.
> 
> Thanks again! @hxcGit
> 
> @daniel-hutao please also have a look; see if it's reasonable.

Got it. I'll think about it later.
