### ISSUE TITLE
:four_leaf_clover: `Proposal`: Plugin `devlake` Enhancement (sub-task with #513)

### ISSUE THREAD

**Issue by daniel-hutao** [devstream-io/devstream#504]
### What would you like to added? Why is this needed?

See #513 for the details

**Comment by daniel-hutao** [comment]
@warren830 Would you like to have a try?

**Comment by IronCore864** [comment]
Requirements: make the plugin for DevLake production-ready.

For example:

- use a helm chart to manage DevLake installation instead of YAML
- use Go helmclient to install instead of kubectl apply
- adjust the amount of numbers of pods of all the deployments so that there is no single point of failure and enough redundancy
- MySQL persistent storage. Local, or other storage? If local, make sure that deleting the MySQL pod won't lose any data.
- Other improvements, for example, add more parameters so that the usage of the plugin can be customized.

**Comment by tobehardest** [comment]
Hello, I want to try to make this, can you assign it to me?
