### ISSUE TITLE
:open_book: `Docs`: Add doc for `develop` commond

### ISSUE THREAD

**Issue by aFlyBird0** [devstream-io/devstream#510]
### What should be changed?

Develop is used to develop a new plugin. However, it seems that there is no doc on the `develop` command

**Comment by daniel-hutao** [comment]
![image](https://user-images.githubusercontent.com/18692628/168991036-4e311c9f-2191-4162-8632-510db398376c.png)

Right, the docs with `develop` are missing.

**Comment by IronCore864** [comment]
We have two blogs on this topic:
- https://blog.devstream.io/posts/creating-a-dtm-plugin-for-anything/
- https://blog.devstream.io/posts/%E7%BB%99dtm%E5%BC%80%E5%8F%91%E4%B8%80%E4%B8%AA%E6%8F%92%E4%BB%B6/

Please use these two as a reference. Also, the command has been updated with more features since the publication of those blogs; so you can enrich the content accordingly. @aFlyBird0

**Comment by daniel-hutao** [comment]
This is a challenge for me. Because English is not my good suit. I wonder if you are interested in adding the missing document?

/cc @IronCore864

**Comment by aFlyBird0** [comment]
> 

I will try my best to finish it, even though it is usually difficult to write documentation.

And it is related to the issue #507 about how how plugin works in devstream.

I will try to finish them together.
