### ISSUE TITLE
:bomb: `Bug`: CI failed in latest prs

### ISSUE THREAD

**Issue by aFlyBird0** [devstream-io/devstream#574]
### What Happened?

![image](https://user-images.githubusercontent.com/36830265/169643229-2a1a0d62-27ac-44f2-aa80-934e5d78f0d3.png)
![image](https://user-images.githubusercontent.com/36830265/169643281-aee4bc20-e61b-4673-80ca-34632c9848e6.png)

### How to Reproduce?

see this [GitHub Action log](https://github.com/devstream-io/devstream/runs/6535038693?check_suite_focus=true) for more details.

### DevStream Version

latest

**Comment by aFlyBird0** [comment]
These for errors were just logged by `log.Errof`

**Comment by aFlyBird0** [comment]
![image](https://user-images.githubusercontent.com/36830265/169646395-110339bd-13be-425a-aa2f-f1732d50d977.png)

**Comment by aFlyBird0** [comment]
I don't think this test error has anything to do with log. I comment all `log.Error` in my fork repo, but it still failed in the test.

(for repo ci report is [here](https://github.com/aFlyBird0/devstream/runs/6536381412?check_suite_focus=true)) 

Maybe It was caused by `TestPlanmanager` in `github.com/devstream-io/devstream/pkg/util/zip`. But I'm not familiar with this code.

![image](https://user-images.githubusercontent.com/36830265/169647841-463cc45f-ead6-49e0-bd9f-f3faf421c841.png)

**Comment by hxcGit** [comment]
https://github.com/devstream-io/devstream/blob/ad784ee8ec5564bfda13999b31b2d371fd6b6d02/internal/pkg/pluginmanager/downloader_test.go#L11

**Comment by KeHaohaoke** [comment]
> These four errors were just logged by `log.Errof`
The last two mistakes in the four mistakes：

The 3rd error: Well, that's because we didn't deliver the files needed for this unit test to s3, our download directory. Later, this problem will be solved soon. We are about to upload the files needed for this unit test.

The 4th error: This is normal, and it passed the test. You can see pass, and you can see the comments in the code:

https://github.com/devstream-io/devstream/blob/main/internal/pkg/pluginmanager/downloader_test.go

**Comment by daniel-hutao** [comment]
https://github.com/devstream-io/devstream/actions/runs/2364889030

/close
