### ISSUE TITLE
:four_leaf_clover: `Proposal`: Use `embed` to read the default config

### ISSUE THREAD

**Issue by iyear** [devstream-io/devstream#603]
## What Would You Like to Add? Why is This Needed?
In `internal/pkg/show/config`, the default config is all written in text. Why not use `embed` to import template files?

This way you can have highlighting and the separate files are easy to maintain.

## Design
All the default config vars are placed in one file(`internal/pkg/show/config/config.go`), and the default config yaml files are placed in the `configs` dir.

Take `githubactions-*` as an example:

```go
var (
	//go:embed configs/githubactions-golang.yaml
	GithubActionsGolangDefaultConfig string
	
	//go:embed configs/githubactions-nodejs.yaml
	GithubActionsNodejsDefaultConfig string

	//go:embed configs/githubactions-python.yaml
	GithubActionsPythonDefaultConfig string
)
```

## Anything else
Similarly, all code that involves templates can be done like this。

Issues that may be affected:
#596 #597 #598

**Comment by daniel-hutao** [comment]
It's so cool! This idea is especially awesome!

Let's discuss a simple design that I think would look like as below:

1. add a `plugins` directory in the `examples` directory, which puts all the template configuration of all the `plugins`, similar to: `argocd.yaml` file contain the default configuration of `argocd`.
2. delete all the files in the `internal/pkg/show/config/plugin` directory, because all the content in it is put under `examples/plugins`
3. update the implementation of the `internal/pkg/show/config` package to include ideas that you can use according to your "talent"
4. `internal/pkg/show/config/defaultconfig.go` can probably be left untouched, because this piece of logic will be refactored soon, I'm working on it. #597

**Comment by iyear** [comment]
@daniel-hutao 

I'm currently having a problem with `go:embed` not working `.` or `..` which means that the parent directory cannot be referenced.

My idea is to leave a `configs` package in examples that reads all these yaml files and provides them to the rest of the program.

Related Issues: 
https://github.com/golang/go/issues/46056
https://github.com/golang/go/issues/41191#issuecomment-686621090

**Comment by daniel-hutao** [comment]
How about to put the yaml files to `internal/pkg/show/config`? @iyear

**Comment by iyear** [comment]
@daniel-hutao The latest commit has moved the plugin yaml default config to that dir, but `quickstart.yaml` will not be read..

I still think the https://github.com/golang/go/issues/41191#issuecomment-686621090 approach is appropriate, as all examples can be exposed to other packages.

**Comment by iyear** [comment]
Or I'll start by making the current `DefaultConfig` standalone as a file. #597 I'll do it later and now I fix this issue.
