### ISSUE TITLE
:four_leaf_clover: `Proposal`: fix: plugin default path

### ISSUE THREAD

**Issue by prodanlabs** [devstream-io/devstream#752]
## What Would You Like to Add? Why Is This Needed?

If the default path of the plugin is the current .devstream, if the user switches the directory, the plugin needs to be downloaded again.

## Design
 The default path of the plugin is in the user's home directory

**Comment by IronCore864** [comment]
@prodanlabs Two suggestions:

1. For a major feature, please discuss with the community first before working on it. In this way, you will be able to use your time more efficiently.
2. Before actually start working on an issue, make sure you always assign the issue to yourself, so that other community members know there is already somebody working on this issue and they won't work on the same.

May I suggest that you read the [the unwritten rules](https://docs.devstream.io/en/latest/contributing_guide/#pull-request-lifecycle) in our contributing guide doc in the pull request lifecycle section? Thanks.

---

On this feature request, I do not agree. Think Terraform as an example:

- You can manage multiple environments of a project, or even multiple projects with DevStream, just like what and how you would do with Terraform.
- Different projects and environments might be created with different versions of DTM plugins. Having a central place (under the HOME) for all projects isn't a best practice here. What if the user wants to delete an environment or a project? He would have to figure out what plugins and which versions are used and only used by this project which he wants to delete.

## Suggestions

Here I suggest we keep the .devstream folder under a working directory (I.E., any folder with a DTM configuration file, which can be stored in a git repo for version control, just like what we would do with Terraform).

Please discuss here @daniel-hutao @aFlyBird0.

**Comment by prodanlabs** [comment]
ok, no problem.
