### ISSUE TITLE
:bomb: `Bug`: command `dtm show config -p harbor` print the wrong config sample

### ISSUE THREAD

**Issue by daniel-hutao** [devstream-io/devstream#841]
### What Happened?

- `./dtm show config -p harbor`

```sh
---
# core config
varFile: "" # If not empty, use the specified external variables config file
toolFile: "" # If not empty, use the specified external tools config file
state: # state config, backend can be local or s3
  backend: local
  options:
    stateFile: devstream.state

---
# plugins config
tools:
  - name: github-repo-scaffolding-golang
    instanceID: default
    options:
      owner: YOUR_GITHUB_USERNAME_CASE_SENSITIVE
      repo: go-webapp-devstream-demo
      branch: main
      image_repo: YOUR_DOCKER_USERNAME/go-webapp-devstream-demo
  - name: githubactions-golang
    instanceID: default
    dependsOn: ["github-repo-scaffolding-golang.default"]
    options:
      owner: YOUR_GITHUB_USERNAME_CASE_SENSITIVE
      repo: go-webapp-devstream-demo
      language:
        name: go
        version: "1.18"
      branch: main
      build:
        enable: True
      test:
        enable: True
        coverage:
          enable: True
      docker:
        enable: False

```

### How to Reproduce?

./dtm show config -p harbor

### DevStream Version

latest

**Comment by iyear** [comment]
The reason occurs in the logic of #794, the `template` param has the default value `quickstart` , and the template is judged first in the `Show` function, so that the logic will always output the configuration of `quickstart`.

https://github.com/devstream-io/devstream/blob/7d186cca87464a3d807ec3f363d80edbaa1acbcb/cmd/devstream/show.go#L64
https://github.com/devstream-io/devstream/blob/68054bedd91467175ab80a8ea152fb1fbe848c8f/internal/pkg/show/config/config.go#L11-L14

The quickest solution is to remove the default value of the `template` parameter.

Or we can discuss how to implement this more elegantly 👏
