### ISSUE TITLE
:four_leaf_clover: `Proposal`: Refactor dev version check

### ISSUE THREAD

**Issue by iyear** [devstream-io/devstream#843]
## What Would You Like to Add? Why Is This Needed?
I opend #821 some days ago, and refactored dev version check.

@hxcGit opened a new PR, using the `semver` package to validate version, I think `semver` covers more situations. So refactoring code are very necessary.

https://github.com/devstream-io/devstream/blob/7edf2749cf3f64c90ccfed626fd58cae6376f043/internal/pkg/version/version.go#L13-L16

He will refactor this in #840. Thanks!

**Comment by hxcGit** [comment]
@iyear  I've checked out this problem. In `semver` we can use `semver.NewConstraint()` to add some constraints and validate them, but the common use is to constrain the version number. 
https://github.com/Masterminds/semver
https://semver.org/

I think it's simpler and clearer to use regular expressions, because we only need to distinguish `dev version` from `release version`. I'm a new user of `semver`, do you have any suggestions?

**Comment by iyear** [comment]
My mistake. I'm sorry.😥

I originally thought that our dev version number was not semver, but now it seems that it is also semver(`0.7.0-130-g805bf48`). So let's stick with the current style. Thanks for your reply!
